### ISSUE TITLE
鸿蒙键盘输入TextInput组件时，点击键盘触发onChange和onChangeText事件，但是输入文本不触发这两个事件。

### ISSUE THREAD

**Issue by tianwei-upup** [react-native-oh-library/react-native-harmony-gesture-handler#24]
### 描述 / Description

鸿蒙键盘输入TextInput组件时，点击键盘触发onChange和onChangeText事件，但是输入文本不触发这两个事件。

### 复现步骤 / Steps to reproduce

1.import { TextInput } from 'react-native-gesture-handler'
2.<TextInput
onChange={()=>{
                    console.log("onChange 被触发 ");
                   
                }}
onChangeText={(newText:string)=>{
                    console.log("拿到变化的文本 "+newText);
                    
                }}
            />
3.向该组件中输入文本，观察log

### 库版本 / Library version

2.14.1

### React Native OpenHarmony version

0.72.27

### 构建类型 / Build type

None

### 设备 / Device

Simulator

### 设备版本 / Device model

Beta5的模拟器

### 已悉知 / Acknowledgements

Yes

**Comment by DemoJiang** [comment]
onChange和onChangeText事件接口功能说明：只有当输入的内容上屏后，输入框内容发生变更才会触发。

1、如果输入中文，当只是输入拼音文本还没上屏时，事件是不触发的，当选中文本后，文本上屏了，事件正常触发，已验证无误；

2、如果是英文输入，由于英文输入是点击键盘后，子母直接上屏，所以会触发onChange和onChangeText事件。

根据以上描述麻烦再次测试下功能。

**Comment by tianwei-upup** [comment]
原代码在next升级版本后问题消失，确认为系统问题
