### ISSUE TITLE
使用PanGestureHandler组件时，鸿蒙端代码报错

### ISSUE THREAD

**Issue by huangxiangsai** [react-native-oh-library/react-native-harmony-gesture-handler#28]
### 描述 / Description

使用PanGestureHandler组件时，鸿蒙端代码报错

Error: Exception in HostFunction: Cannot read property getViewByTag of undefined

个人分析： 

报错具体代码位置： RNGestureHandlerModule.ts 文件， attachGestureHandler 方法
报错代码行：let view = this.viewRegistry.getViewByTag(viewTag)

根据上述报错提示，应该就是this.viewRegistry 不存在导致的 ， 而 this.viewRegistry 在该文件，另外一个install方法中被赋值

但查看源码，没有找到调用install方法 的地方 

### 复现步骤 / Steps to reproduce

前端RN组件中引用 PanGestureHandler 组件

### 库版本 / Library version

2.14.7

### React Native OpenHarmony version

0.27.72

### 构建类型 / Build type

None

### 设备 / Device

None

### 已悉知 / Acknowledgements

Yes

**Comment by huangxiangsai** [comment]
该问题已解决， 需要手动调用 TurboModule上的install方法， 但PanGestureHandler 上的事件不触发，onGestureHandlerEvent onGestureHandlerStateChange 这两个事件都不触发

**Comment by huangxiangsai** [comment]
没有触发事件有几个原因：
 1.  没有使用GestureHandlerRootView 作为PanGestureHandler的父组件
 2. 但即使使用了GestureHandlerRootView，也有概率不触发事件，由于PanGestureHandler子组件上的样式，可能会使得实际展示时，PanGestureHandler组件没有被GestureHandlerRootView组件包裹，从而导致事件无法触发
 
实际的组件展示如下图时，就会出现事件不触发的情况
![](https://imagev2.xmcdn.com/storages/6933-audiofreehighqps/9D/95/GKwRIJIK5pYXAAMrbwMgJQWa.jpg)

iOS ,Android 支持只使用PanGestureHandler组件的，不需要GestureHandlerRootView组件包裹

**Comment by Louis-C7** [comment]
> viewRegistry

您好，在react-native-gesture-handler@2.x以上的版本里，安卓上也是需要包裹GestureHandlerRootView组件的。旧版本在安卓上提供了原生端设置GestureHandlerRootView的方法，2.x以上版本已经不推荐这么使用。详情请见官方的说明：https://docs.swmansion.com/react-native-gesture-handler/docs/guides/migrating-off-rnghenabledroot

2.x以上版本的PanGestureHandler组件官方使用示例：https://docs.swmansion.com/react-native-gesture-handler/docs/gesture-handlers/pan-gh#example
