### ISSUE TITLE
import { TM } from "@rnoh/react-native-openharmony/generated/ts" 找不到

### ISSUE THREAD

**Issue by xp19870106** [react-native-oh-library/react-native-harmony-gesture-handler#30]
# Question

RNGestureHandlerModule.ts文件会提示
import { TM } from "@rnoh/react-native-openharmony/generated/ts" 找不到

我编译出来的react-native-openharmony/也确实没有这个generated路径

**Comment by xp19870106** [comment]
已经解决了

**Comment by suiyunpiaoliu** [comment]
@xp19870106 ,请问是如何解决这个问题的

**Comment by xp19870106** [comment]
> @xp19870106 ,请问是如何解决这个问题的

https://gitee.com/react-native-oh-library/usage-docs/blob/master/zh-cn/codegen.md

**Comment by xp19870106** [comment]
> @xp19870106 ,请问是如何解决这个问题的

https://gitee.com/react-native-oh-library/usage-docs/blob/master/zh-cn/codegen.md
