### ISSUE TITLE
使用PanGestureHandler的时候鸿蒙上会报错

### ISSUE THREAD

**Issue by xp19870106** [react-native-oh-library/react-native-harmony-gesture-handler#31]
### 描述 / Description

版本：react-native-oh-tpl-react-native-gesture-handler-2.14.14-rc.1

### 复现步骤 / Steps to reproduce

`
import React, { Component } from "react";
import { Animated, Dimensions } from "react-native";
import {
  GestureHandlerRootView,
  PanGestureHandler,
} from "react-native-gesture-handler";

const { width } = Dimensions.get("screen");
const circleRadius = 30;

class Circle extends Component {
  _touchX = new Animated.Value(width / 2 - circleRadius);

  _onPanGestureEvent = Animated.event([{ nativeEvent: { x: this._touchX } }], {
    useNativeDriver: true,
  });

  render() {
    return (
      <GestureHandlerRootView>
        <PanGestureHandler onGestureEvent={this._onPanGestureEvent}>
          <Animated.View
            style={{
              height: 150,
              justifyContent: "center",
            }}
          >
            <Animated.View
              style={[
                {
                  backgroundColor: "#42a5f5",
                  borderRadius: circleRadius,
                  height: circleRadius * 2,
                  width: circleRadius * 2,
                },
                {
                  transform: [
                    {
                      translateX: Animated.add(
                        this._touchX,
                        new Animated.Value(-circleRadius)
                      ),
                    },
                  ],
                },
              ]}
            />
          </Animated.View>
        </PanGestureHandler>
      </GestureHandlerRootView>
    );
  }
}

export default function App() {
  return <Circle />;
}
`

### 库版本 / Library version

react-native-oh-tpl-react-native-gesture-handler-2.14.14-rc.1.tgz

### React Native OpenHarmony version

rnoh-react-native-harmony-0.72.32.tgz

### 构建类型 / Build type

None

### 设备 / Device

None

### 已悉知 / Acknowledgements

Yes

**Comment by Louis-C7** [comment]
请参考官方文档中的使用示例：https://docs.swmansion.com/react-native-gesture-handler/docs/gesture-handlers/pan-gh#example
